
# 📝 실전 문제풀이 Set 2: 갤럭시 사용자 데이터 분석

## 1) 데이터 및 시나리오

▶ 디지털 기기 취급 전문업체 DigiSales는 오프라인 매장에서 갤럭시 제품군을 구매한 이력이 있는 사람들의 단말기 이용 행태를 분석하기 위해 통신사 MT로부터 익명화 처리된 고객 정보를 일부 구매하였다. 해당 데이터에서 인사이트를 뽑기 위해 다양한 분석을 해보고자 한다.

* **데이터 개요:** `galaxy_users.csv` (7032 rows, 21 columns, UTF-8)

**[변수 상세]**

| 변수명 | 유형 | 설명 |
| --- | --- | --- |
| `customerID` | string | 고객 식별자 |
| `gender` | string | 성별 |
| `Senior Citizen` | int | 시니어 여부(1: 시니어, 0: 아님) |
| `Partner` | string | 배우자 존재 여부(Yes, No) |
| `Dependents` | string | 부양가족(Yes, No) |
| `tenure` | int | 현 직장 근속 월수 |
| `PhoneService` | string | 단말 서비스 사용 여부(Yes, No) |
| `MultipleLines` | string | 다중 회선 개통 여부(Yes, No) |
| `InternetService` | string | 인터넷 사용(DSL, Fiber optic, No) |
| `OnlineSecurity` | string | 온라인 보안 서비스(Yes, No) |
| `OnlineBackup` | string | 온라인 백업 서비스(Yes, No) |
| `Device Protection` | string | 기기 보호 서비스(Yes, No) |
| `TechSupport` | string | 기술 지원 서비스(Yes, No) |
| `Streaming TV` | string | 스트리밍 지원 TV(Yes, No) |
| `Streaming Movies` | string | 영화 스트리밍 서비스(Yes, No) |
| `Contract` | string | 계약 갱신 주기 |
| `PaperlessBilling` | string | 온라인 명세서 발급 서비스(Yes, No) |
| `Payment Method` | string | 납부 방법 |
| `MonthlyCharges` | float | 월별 청구 금액 |
| `TotalCharges` | float | 누적 청구 금액 |
| `Churn` | string | 이탈 여부(Yes: 이탈, No: 잔존) |

## 2) 문제

* **필요 라이브러리:** 
```python
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
```

### **Q01.** 부가 서비스를 많이 사용할수록 제품 또는 브랜드에 고관여 되어있다는 가설을 세우고 분석을 하고자 한다. 이에 앞서 고객별 부가서비스 사용 현황 통계를 산출하고자 한다. **부가 서비스를 1개 사용하는 사람은 부가 서비스를 6개 사용하는 사람보다 몇 배나 많은지 계산하시오.**

* ※ 부가서비스 대상 변수: OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, Streaming TV, Streaming Movies
* ※ 부가서비스 변수의 범주가 "Yes"인 경우 1로, "No"는 0으로 간주한다.
* ※ 부가서비스 변수에 "Yes" 또는 "No"가 아닌 다른 범주가 있는 경우 해당 행은 제거 후 분석하시오.
* ※ 정답은 반올림하여 소수점 첫째 자리까지 출력하시오. (정답 예시: 1.2)

### **Q02.** 여러 변수간 상관관계를 확인하고자 한다. **현 직장 근속 월수(tenure), 월별 청구 금액(MonthlyCharges), 통신사 사용 월수 간 피어슨 상관분석을 실시하고 그 결과 중 상관계수 절대값이 가장 높은 것을 확인하시오.**

* ※ 통신사 사용 월수는 총 청구금액(TotalCharges)을 월별 청구금액(MonthlyCharges)으로 나눈 값의 몫으로 한다.
* ※ 정답은 반올림하여 소수점 셋째 자리까지 출력하시오. (정답 예시: 0.123)

### **Q03.** 고객 이탈여부(Churn)를 종속변수로 하는 모델을 만들어보고자 한다. 데이터 분할 후 정규화를 실시하여 로지스틱 회귀분석을 실시하고 해당 모델을 기준점 삼아 모델을 개선하고자 한다. **주어진 독립변수를 활용하여 F1-score로 모델을 평가하시오.**

* `<독립변수>`: 시니어 여부, 파트너 존재 여부, 부양가족 존재 여부, 현 직장 근속 개월 수, 월별 청구 금액, 누적 청구 금액, 온라인 보안 서비스, 온라인 백업 서비스, 기기 보호 서비스, 기술 지원 서비스, 영화 스트리밍 서비스, 온라인 명세서 발급 서비스
* `<종속변수>`: 고객 이탈여부
* ※ 범주형 변수의 범주가 "Yes"인 경우 1로, "No"인 경우 0으로 치환하며, 나머지 범주는 -1로 치환하시오.
* ※ 학습 및 평가 데이터 세트 분할비는 7:3으로 하시오.
* ※ Min-Max 정규화를 실시하며(모든 변수 대상), 평가 데이터 세트는 학습 데이터 세트 기반으로 정규화 하시오.
* ※ seed는 123으로 고정하시오.
* ※ 정답은 반올림하여 소수점 둘째 자리까지 출력하시오. (정답 예시: 0.12)

---

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score

In [5]:
df = pd.read_csv("../dataset/galaxy_users.csv")
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [6]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7028,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7029,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7030,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7031,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

### **Q01.** 부가 서비스를 많이 사용할수록 제품 또는 브랜드에 고관여 되어있다는 가설을 세우고 분석을 하고자 한다. 이에 앞서 고객별 부가서비스 사용 현황 통계를 산출하고자 한다. **부가 서비스를 1개 사용하는 사람은 부가 서비스를 6개 사용하는 사람보다 몇 배나 많은지 계산하시오.**

* ※ 부가서비스 대상 변수: OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, Streaming TV, Streaming Movies
* ※ 부가서비스 변수의 범주가 "Yes"인 경우 1로, "No"는 0으로 간주한다.
* ※ 부가서비스 변수에 "Yes" 또는 "No"가 아닌 다른 범주가 있는 경우 해당 행은 제거 후 분석하시오.
* ※ 정답은 반올림하여 소수점 첫째 자리까지 출력하시오. (정답 예시: 1.2)

---
#### 한번에

In [65]:
df_q1 = df.loc[:,"OnlineSecurity" : "StreamingMovies"].copy()
cond1 = df_q1.isin(["Yes", "No"]).all(axis = 1)
df_q1_2 = df_q1[cond1].replace({"Yes" : 1, "No" : 0})
ser_q1 = df_q1_2.sum(axis = 1).value_counts()
round(ser_q1[1]/ser_q1[6],2)

3.4

---
#### 단계별

In [25]:
df_q1_ = df[['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']].copy()

In [56]:
df_q1_.isin(['Yes','No'])

,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,True,True,True,True,True,True
1,True,True,True,True,True,True
2,True,True,True,True,True,True
3,True,True,True,True,True,True
4,True,True,True,True,True,True
...,...,...,...,...,...,...
7027,True,True,True,True,True,True
7028,True,True,True,True,True,True
7029,True,True,True,True,True,True
7030,True,True,True,True,True,True
7031,True,True,True,True,True,True

In [26]:
cond1_ = df_q1_.isin(['Yes','No']).all(axis=1)
cond1_

0       True
1       True
2       True
3       True
4       True
        ...
7027    True
7028    True
7029    True
7030    True
7031    True
Length: 7032, dtype: bool

In [29]:
df_q1_cond1_ = df_q1_[cond1_]
df_q1_cond1_

,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,No,Yes,No,No,No,No
1,Yes,No,Yes,No,No,No
2,Yes,Yes,No,No,No,No
3,Yes,No,Yes,Yes,No,No
4,No,No,No,No,No,No
...,...,...,...,...,...,...
7027,Yes,No,Yes,Yes,Yes,Yes
7028,No,Yes,Yes,No,Yes,Yes
7029,Yes,No,No,No,No,No
7030,No,No,No,No,No,No
7031,Yes,No,Yes,Yes,Yes,Yes

In [34]:
df_q1_cond1_ = df_q1_cond1_.replace({"Yes" : 1, "No" : 0})
df_q1_cond1_

,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,0,1,0,0,0,0
1,1,0,1,0,0,0
2,1,1,0,0,0,0
3,1,0,1,1,0,0
4,0,0,0,0,0,0
...,...,...,...,...,...,...
7027,1,0,1,1,1,1
7028,0,1,1,0,1,1
7029,1,0,0,0,0,0
7030,0,0,0,0,0,0
7031,1,0,1,1,1,1

In [39]:
df_q1_count_ = df_q1_cond1_.sum(axis = 1)
df_q1_count_

0       1
1       2
2       2
3       3
4       0
       ..
7027    5
7028    4
7029    1
7030    0
7031    5
Length: 5512, dtype: int64

In [46]:
df_q1_sum_ = df_q1_count_.value_counts()
type(df_q1_sum_) , df_q1_sum_

(pandas.core.series.Series,
 3    1117
 2    1033
 1     966
 4     850
 0     693
 5     569
 6     284
 dtype: int64)

In [47]:
round(df_q1_sum_[1]/df_q1_sum_[6],2)

3.4

### **Q02.** 여러 변수간 상관관계를 확인하고자 한다. **현 직장 근속 월수(tenure), 월별 청구 금액(MonthlyCharges), 통신사 사용 월수 간 피어슨 상관분석을 실시하고 그 결과 중 상관계수 절대값이 가장 높은 것을 확인하시오.**

* ※ 통신사 사용 월수는 총 청구금액(TotalCharges)을 월별 청구금액(MonthlyCharges)으로 나눈 값의 몫으로 한다.
* ※ 정답은 반올림하여 소수점 셋째 자리까지 출력하시오. (정답 예시: 0.123)

#### 한번에
---

In [86]:
df_q2 = df[['tenure','MonthlyCharges']].copy()
df_q2['var1'] = df['TotalCharges']//df['MonthlyCharges']
df_q2_corr_abs = df_q2.corr(method='pearson').abs()
np.fill_diagonal(df_q2_corr_abs.values, 0) # 자기자신은 1이므로 이걸 최소 절대값으로 바꾸려고
#np는 dataframe(행,열,값) 을 못쓰므로 values를 써서 (값배열)로만 해줘야함
round(df_q2_corr_abs.max().max(),3)

0.999

#### 단계별
---

In [88]:
df_q2_ = df[['tenure','MonthlyCharges']].copy()
df_q2_['var1'] = df['TotalCharges']//df['MonthlyCharges']
df_q2_

      tenure  MonthlyCharges  var1
0          1           29.85   1.0
1         34           56.95  33.0
2          2           53.85   2.0
3         45           42.30  43.0
4          2           70.70   2.0
...      ...             ...   ...
7027      24           84.80  23.0
7028      72          103.20  71.0
7029      11           29.60  11.0
7030       4           74.40   4.0
7031      66          105.65  64.0

[7032 rows x 3 columns]

상관계수는 dataframe에서 corr(method = 'pearson') 을 쓰면 된다.
기본은 pearson이나 method = 'spearman' 으로도 쓸 수 있다

In [90]:
df_q2_corr_ = df_q2_.corr(method = 'pearson')
df_q2_corr_

                  tenure  MonthlyCharges      var1
tenure          1.000000        0.246862  0.998831
MonthlyCharges  0.246862        1.000000  0.246164
var1            0.998831        0.246164  1.000000

In [92]:
df_q2_corr_abs_ = df_q2_corr_.abs()
df_q2_corr_abs_

                  tenure  MonthlyCharges      var1
tenure          1.000000        0.246862  0.998831
MonthlyCharges  0.246862        1.000000  0.246164
var1            0.998831        0.246164  1.000000

In [93]:
np.fill_diagonal(df_q2_corr_abs_.values, 0)
df_q2_corr_abs_

                  tenure  MonthlyCharges      var1
tenure          0.000000        0.246862  0.998831
MonthlyCharges  0.246862        0.000000  0.246164
var1            0.998831        0.246164  0.000000

In [96]:
max_per_col = df_q2_corr_abs_.max()
max_per_col

tenure            0.998831
MonthlyCharges    0.246862
var1              0.998831
dtype: float64

In [98]:
max_per_all = max_per_col.max()
max_per_all , df_q2_corr_abs_.max().max()

(0.9988308750302998, 0.9988308750302998)

In [99]:
round(max_per_all, 3)

0.999

### **Q03.** 고객 이탈여부(Churn)를 종속변수로 하는 모델을 만들어보고자 한다. 데이터 분할 후 정규화를 실시하여 로지스틱 회귀분석을 실시하고 해당 모델을 기준점 삼아 모델을 개선하고자 한다. **주어진 독립변수를 활용하여 F1-score로 모델을 평가하시오.**

* `<독립변수>`: 시니어 여부, 파트너 존재 여부, 부양가족 존재 여부, 현 직장 근속 개월 수, 월별 청구 금액, 누적 청구 금액, 온라인 보안 서비스, 온라인 백업 서비스, 기기 보호 서비스, 기술 지원 서비스, 영화 스트리밍 서비스, 온라인 명세서 발급 서비스
* `<종속변수>`: 고객 이탈여부
* ※ 범주형 변수의 범주가 "Yes"인 경우 1로, "No"인 경우 0으로 치환하며, 나머지 범주는 -1로 치환하시오.
* ※ 학습 및 평가 데이터 세트 분할비는 7:3으로 하시오.
* ※ Min-Max 정규화를 실시하며(모든 변수 대상--> 독립변수 의미 종속변수 아님), 평가 데이터 세트는 학습 데이터 세트 기반으로 정규화 하시오.
* ※ seed는 123으로 고정하시오.
* ※ 정답은 반올림하여 소수점 둘째 자리까지 출력하시오. (정답 예시: 0.12)

#### 한번에
---

In [ ]:
var_X = ["SeniorCitizen", "Partner", "Dependents", "tenure", "MonthlyCharges", "TotalCharges", "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingMovies", "PaperlessBilling"].copy()
var_y = ["Churn"]
df_q3 = df[var_X + var_y] #독립, 종속은 같은 df에 넣는 습관이 문제풀이 좋음

def series_convert(x) :
    if x == "Yes" :
        return 1
    if x == "No" :
        return 0
    return -1

def dataframe_convert_object(col) : #return을 반드시
    if col.dtype == "object" :
        return col.apply(series_convert)
    return col #제일중요함, return 안하면 None 출력
df_q3_cond = df_q3.apply(dataframe_convert_object)

#df_q3_cond.isin([-1]).sum() 
#찾고자하는 값이 몇개있는지 세려면 count 가 아닌 sum, isin은 true/false를 리턴
#count는 "결측치가 아닌 개수"를 리턴
X = df_q3[var_X]
y = df_q3[var_y]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3, random_state= 123)
X_train_scaled = MinMaxScaler().fit_transform(X_train)

#### 단계별
---