## 📝 실전 문제풀이 Set 1: 시중 TV 제품별 분석

### 1) 데이터 및 시나리오

▶ 시중 판매 중인 TV 정보를 온라인 쇼핑몰 웹페이지에서 크롤링하여 분석하고자 한다. 해당 데이터를 기반으로 각 TV의 제원은 어떠한지, 제원에 따른 평가는 어떠한지 알아보고 향후 신제품 출시에 참고하고자 한다.

* **데이터 개요:** `Xa TV.csv` (666 rows, 11 columns, UTF-8)

**[변수 상세]**

| 변수명 | 유형 | 설명 |
| --- | --- | --- |
| `Product_Name` | string | 상품명 |
| `Stars` | float | 평가 평균 점수 |
| `Ratings` | int | 평가 수 |
| `Reviews` | int | 후기 수 |
| `current_price` | int | 현재 가격 |
| `MRP` | int | 출고가 |
| `channel` | string | 판매 채널 / 공장 정보 등 |
| `Operating_system` | string | 운영체제 |
| `Picture_quality` | string | 해상도 |
| `Speaker` | string | 스피커 |
| `Frequency` | string | 주사율 |


* **필요 라이브러리:** `from sklearn.ensemble import RandomForestRegressor`

In [2]:
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestRegressor

In [4]:
df = pd.read_csv("../dataset/TV.csv")
df.shape

(666, 11)

In [5]:
df.head(20)

,Product_Name,Stars,Ratings,Reviews,current_price,MRP,channel,Operating_system,Picture_quality,Speaker,Frequency
0,Croma,4.2,1773,217,7990,20000,HD Ready 1366 x 768 Pixels,20 Speaker Output,60 Hz Refresh Rate,2 x HDMI | 2 x USB,1 Year Warranty
1,Adsun,3.8,6742,930,8699,21999,Netflix|Disney+Hotstar|Youtube,Operating System: Android Based,HD Ready 1366 x 768 Pixels,20 W Speaker Output,60 Hz Refresh Rate
2,LG,4.4,38870,3443,16499,21990,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: WebOS,HD Ready 1366 x 768 Pixels,10 W Speaker Output,50 Hz Refresh Rate
3,OnePlus,4.3,101256,9189,16499,21999,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,HD Ready 1366 x 768 Pixels,20 W Speaker Output,60 Hz Refresh Rate
4,Xiaomi,4.3,3120,305,15499,24999,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,HD Ready 1366 x 768 Pixels,20 W Speaker Output,60 Hz Refresh Rate
5,SAMSUNG,4.4,53639,4811,15999,22900,Netflix|Disney+Hotstar|Youtube,Operating System: Tizen,HD Ready 1366 x 768 Pixels,20 W Speaker Output,60 Hz Refresh Rate
6,OnePlus,4.3,101256,9189,15499,19999,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,HD Ready 1366 x 768 Pixels,20 W Speaker Output,60 Hz Refresh Rate
7,Croma,4.2,0,0,11990,25000,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,HD Ready 1366 x 768 Pixels,20 Speaker Output,60 Hz Refresh Rate
8,LG,4.4,5830,698,32990,59990,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: WebOS,Ultra HD (4K) 3840 x 2160 Pixels,20 W Speaker Output,60 Hz Refresh Rate
9,OnePlus,4.3,101256,9189,25999,31999,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,Full HD 1920 x 1080 Pixels,20 W Speaker Output,60 Hz Refresh Rate
10,Vu,4.4,32043,4978,30990,45000,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,Ultra HD (4K) 3840 x 2160 Pixels,30 W Speaker Output,60 Hz Refresh Rate
11,Adsun,3.8,6742,930,8999,29999,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android Based,HD Ready 1366 x 768 Pixels,20 W Speaker Output,60 Hz Refresh Rate
12,OnePlus,4.3,101256,9189,22999,27999,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,Full HD 1920 x 1080 Pixels,20 W Speaker Output,60 Hz Refresh Rate
13,MarQ,4.2,6251,764,8999,19999,HD Ready 1366 X 768 Pixels,20 W Speaker Output,60 Hz Refresh Rate,2 x HDMI | 2 x USB,1 Year Warranty on Product
14,OnePlus,4.3,101256,9189,24999,29999,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,Full HD 1920 x 1080 Pixels,20 W Speaker Output,60 Hz Refresh Rate
15,Croma,3.9,0,0,18990,30000,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,Full HD 1920 x 1080 Pixels,20 Speaker Output,60 Hz Refresh Rate
16,Xiaomi,4.3,3120,305,22999,29999,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,Full HD 1920 x 1080 Pixels,24 W Speaker Output,60 Hz Refresh Rate
17,Vu,4.2,5635,632,12999,20000,Netflix|Prime Video|Youtube,Operating System: Linux,HD Ready 1366 x 768 Pixels,20 W Speaker Output,60 Hz Refresh Rate
18,Mi,4.3,40877,3658,31999,49999,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,Ultra HD (4K) 3840 x 2160 Pixels,30 W Speaker Output,60 Hz Refresh Rate
19,Adsun,3.8,6742,930,16999,39999,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android Based,Full HD 1920 x 1080 Pixels,20 W Speaker Output,60 Hz Refresh Rate

**Q01.** 주사율(Frequency)은 TV 제원 중 가격에 큰 영향을 미치는 제원이다. 그런데 데이터 수집 중 실수가 발생하여 주사율(Frequency) 값 중 일부가 해상도(Picture_quality), 스피커(Speaker) 변수에 잘못 입력된 것이 발견되었다. 세 변수에 흩어져 있는 주사율 데이터를 취합하여 전체 TV 중에서 **주사율이 60Hz인 TV는 총 몇 대 인가?**

* ※ 주사율은 2~3자리 숫자 뒤에 반드시 Hz라는 단위로 표기되어 있다.
* ※ 세 변수 모두 주사율 정보가 없을 경우 결측치로 간주하고 이를 분석에서 제외하시오. (정답 예시: 12)

```plain text
picture_quality, speaker, Frequency 세 변수에 60HZ를 찾는 것.
하나의 col으로 관리한 뒤 

그리고 60HZ를 찾는다.
```

In [24]:
#문자열 합칠 때를 생각하면 fillna(' ')로 하는 것이 좋다. fillna('')로 하면 문자열이 붙어서 60Hz가 60Hz로 붙어서 검색이 안될 수 있다.
df_q1 = df['Frequency'].fillna(' ') +' ' + df['Picture_quality'].fillna(' ') + ' '  + df['Speaker'].fillna(' ')
cond1 = df_q1.str.contains(r"(?<!\d)60\s*Hz", case=False, regex=True)
cond1.sum()

510

### 단계별 풀이

In [7]:
df_q1 = df[["Frequency", "Picture_quality", "Speaker"]].copy()
df_q1.head(10)

            Frequency                   Picture_quality              Speaker
0     1 Year Warranty                60 Hz Refresh Rate   2 x HDMI | 2 x USB
1  60 Hz Refresh Rate        HD Ready 1366 x 768 Pixels  20 W Speaker Output
2  50 Hz Refresh Rate        HD Ready 1366 x 768 Pixels  10 W Speaker Output
3  60 Hz Refresh Rate        HD Ready 1366 x 768 Pixels  20 W Speaker Output
4  60 Hz Refresh Rate        HD Ready 1366 x 768 Pixels  20 W Speaker Output
5  60 Hz Refresh Rate        HD Ready 1366 x 768 Pixels  20 W Speaker Output
6  60 Hz Refresh Rate        HD Ready 1366 x 768 Pixels  20 W Speaker Output
7  60 Hz Refresh Rate        HD Ready 1366 x 768 Pixels    20 Speaker Output
8  60 Hz Refresh Rate  Ultra HD (4K) 3840 x 2160 Pixels  20 W Speaker Output
9  60 Hz Refresh Rate        Full HD 1920 x 1080 Pixels  20 W Speaker Output

In [25]:
df_com = df['Frequency'].fillna(' ') +' '  \
        + df['Picture_quality'].fillna(' ')+' ' \
        + df['Speaker'].fillna(' ')
df_com.head(10)
df_com

0      1 Year Warranty 60 Hz Refresh Rate 2 x HDMI | ...
1      60 Hz Refresh Rate HD Ready 1366 x 768 Pixels ...
2      50 Hz Refresh Rate HD Ready 1366 x 768 Pixels ...
3      60 Hz Refresh Rate HD Ready 1366 x 768 Pixels ...
4      60 Hz Refresh Rate HD Ready 1366 x 768 Pixels ...
                             ...
661         1 YEAR 60 Hz Refresh Rate 2 x HDMI | 1 x USB
662    50 Hz Refresh Rate Ultra HD (4K) 3840 x 2160 P...
663    3 Years Warranty 60 Hz Refresh Rate 2 x HDMI |...
664    2 x HDMI | 2 x USB 16 Speaker Output 50 Hz Ref...
665         1 YEAR 50 Hz Refresh Rate 2 x HDMI | 2 x USB
Length: 666, dtype: object

#### 방법1 str.contains로 true false로 찾기

In [9]:
df_com.str.contains("60 Hz")

0       True
1       True
2      False
3       True
4       True
       ...
661     True
662    False
663     True
664    False
665    False
Length: 666, dtype: bool

In [10]:
df_com.str.contains("60 Hz").sum()

510

#### 방법2. 방법1은 datafram에 넣으면 조건으로 사용되서 조건에 해당하는 행만 뽑는 새로운 dataframe을 만들 수 있음.

In [11]:
cond1 = df_com.str.contains("60 Hz")
df_result1 = df_com[cond1]
df_result1

0      1 Year Warranty60 Hz Refresh Rate2 x HDMI | 2 ...
1      60 Hz Refresh RateHD Ready 1366 x 768 Pixels20...
3      60 Hz Refresh RateHD Ready 1366 x 768 Pixels20...
4      60 Hz Refresh RateHD Ready 1366 x 768 Pixels20...
5      60 Hz Refresh RateHD Ready 1366 x 768 Pixels20...
                             ...
656    60 Hz Refresh RateUltra HD (4K) 3840 x 2160 Pi...
659    1 Year Warranty60 Hz Refresh Rate2 x HDMI | 2 ...
660    A+ Grade Panel60 Hz Refresh Rate2 x HDMI | 2 x...
661           1 YEAR60 Hz Refresh Rate2 x HDMI | 1 x USB
663    3 Years Warranty60 Hz Refresh Rate2 x HDMI | 2...
Length: 510, dtype: object

In [12]:
len(df_result1)

510


O Years Warranty60 Hz Refre  
X 260HZ  
O 60 HZ  
이어야 해서 앞자리에 숫자가 오면 안된다.
```
r"(?<!\d)60\s*Hz"
```
- ~가 오면 안된다 정규식 : (?<! {안되는 대상})
  ```
  1. 숫자가 안됨 : \d, [0-9]
    (?<!\d)
  2. 영어가 안됨 : [a-zA-Z]
    (?<![a-zA-Z])
  3. 숫자 영어 안됨 : [a-zA-Z0-9]
    (?<![0-9a-zA-Z])
  ```

In [13]:
cond2 = df_com.str.contains(r"(?<![0-9])60\s*Hz", case=False, regex=True)
cond2.sum()

510

**Q02.** TV의 해상도(Picture_quality)는 HD, 4K, 8K로 나뉜다. 최근 시장에 등장한 8K 제품군은 상대적으로 비싸 비교적 매출이 떨어지는 편이다. 하지만 8K 제품군 구매자가 4K 제품군 구매자 대비 얼마나 만족하고 있는지 확인해보고자 한다. **8K 제품군의 평가 평균 점수(Stars)의 평균값과 4K 제품군의 평가 평균 점수와의 평균값 차이의 절대값을 산출하시오.**

* ※ 화면 해상도는 관련 변수에서 "HD", "4K", "8K"로 찾아낼 수 있다.
* ※ 화면 해상도 정보는 "Operating_system", "channel", "Picture_quality" 변수에 흩어져 있다.
* ※ 결과는 반올림하여 소수점 둘째 자리까지 출력하시오. (정답 예시: 0.12)

In [42]:
df_q2 = df[['Operating_system', 'channel', 'Picture_quality','Stars']].copy()
df_q2_4k = df_q2.loc[df_q2['Operating_system'].str.contains('4K') 
                     | df_q2['channel'].str.contains('4K') 
                     | df_q2['Picture_quality'].str.contains('4K'),"Stars"].mean()
df_q2_8k = df_q2.loc[df_q2['Operating_system'].str.contains('8K') 
                     | df_q2['channel'].str.contains('8K') 
                     | df_q2['Picture_quality'].str.contains('8K'),"Stars"].mean()
df_q2_4k, df_q2_8k
round(abs(df_q2_4k - df_q2_8k), 2)

0.38

---

In [37]:
df_q2 = df[['Operating_system', 'channel', 'Picture_quality','Stars']].copy()
df_q2.head(10)

,Operating_system,channel,Picture_quality,Stars
0,20 Speaker Output,HD Ready 1366 x 768 Pixels,60 Hz Refresh Rate,4.2
1,Operating System: Android Based,Netflix|Disney+Hotstar|Youtube,HD Ready 1366 x 768 Pixels,3.8
2,Operating System: WebOS,Netflix|Prime Video|Disney+Hotstar|Youtube,HD Ready 1366 x 768 Pixels,4.4
3,Operating System: Android,Netflix|Prime Video|Disney+Hotstar|Youtube,HD Ready 1366 x 768 Pixels,4.3
4,Operating System: Android,Netflix|Prime Video|Disney+Hotstar|Youtube,HD Ready 1366 x 768 Pixels,4.3
5,Operating System: Tizen,Netflix|Disney+Hotstar|Youtube,HD Ready 1366 x 768 Pixels,4.4
6,Operating System: Android,Netflix|Prime Video|Disney+Hotstar|Youtube,HD Ready 1366 x 768 Pixels,4.3
7,Operating System: Android,Netflix|Prime Video|Disney+Hotstar|Youtube,HD Ready 1366 x 768 Pixels,4.2
8,Operating System: WebOS,Netflix|Prime Video|Disney+Hotstar|Youtube,Ultra HD (4K) 3840 x 2160 Pixels,4.4
9,Operating System: Android,Netflix|Prime Video|Disney+Hotstar|Youtube,Full HD 1920 x 1080 Pixels,4.3

In [ ]:
df_q2_com = df_q2[['Stars']].copy() #괄호를 하나만 쓰면 시리즈로 나오고, 두개를 쓰면 데이터프레임으로 나온다.
df_q2_com['is_4k']=df_q2.iloc[:,0:3].apply(lambda x: x.str.contains('4K',case=False).sum(), axis = 1)
df_q2_com['is_8k']=df_q2.iloc[:,0:3].apply(lambda x: x.str.contains('8K',case=False).sum(), axis = 1)
df_q2_com.head(10)

   Stars  is_4k  is_8k
0    4.2      0      0
1    3.8      0      0
2    4.4      0      0
3    4.3      0      0
4    4.3      0      0
5    4.4      0      0
6    4.3      0      0
7    4.2      0      0
8    4.4      1      0
9    4.3      0      0

In [35]:
mean_4k = df_q2_com.loc[df_q2_com['is_4k'] == 1, "Stars"].mean()
mean_8k = df_q2_com.loc[df_q2_com['is_8k'] == 1, "Stars"].mean()
mean_4k, mean_8k

(3.2180821917808218, 3.6)

In [ ]:
round(abs(mean_4k - mean_8k), 2)

0.38

**Q03.** 좋은 평가를 받는 제품의 조건을 알아보고자 한다. 이를 위해 기존 변수와 더불어 여러 파생변수를 생성 후 해당 변수를 독립변수로 하고 평가 평균 점수(Stars)를 종속변수로 하여 Random Forest 분석을 통해 좋은 평가를 받는 제품의 조건을 알아보고자 한다. 아래 절차를 수행하여 변수 중요도를 확인하고, **변수 중요도 값 중 가장 큰 값을 가진 변수명을 기술하시오.**

* `<독립변수>`
* var1 = 후기 작성 비율: 후기 수(Reviews) / 평가 수(Ratings)
* var2 = 공장 출고가(MRP)
* var3 = 할인율: 현재 판매가(current_price) / 공장 출고가(MRP)
* var4 = Netflix 제공 여부: 제공(1), 미제공(0)
* var5 = Prime Video 제공 여부: 제공(1), 미제공(0)
* var6 = 고해상도 여부: 4K 또는 8K(1), 나머지(0)


* `<종속변수>`
* 평가 평균 점수(Stars)


* ※ channel 변수에 해상도('Pixel' 문자 참조) 또는 운영체제 정보('Oper' 문자 참조)가 있는 TV는 분석에서 제외하시오.
* ※ Netflix와 Prime Video 제공 여부 변수는 channel 변수를 참고하시오.
* ※ 독립변수를 생성하면서 결측치가 생성되는 경우 해당 행을 모두 제거하시오.
* ※ 학습 대상이 되는 행 개수는 197이다.
* ※ 고해상도 여부 변수 생성은 해상도(Picture_quality) 변수만 참고하여 생성하시오.
* ※ seed는 123으로 지정하시오. (정답 예시: 고해상도여부 - 띄어쓰지 않고 문제에서 제시된 독립변수 명을 기입)

## 한번에

In [131]:
df_q3_ = df.copy()
df_q3_= df_q3_.loc[~df_q3_['channel'].str.contains('Oper|Pixel'),]
df_q3_com_ = pd.DataFrame()
df_q3_com_['Stars'] = df_q3_['Stars']
df_q3_com_['var1'] = df_q3_['Reviews'] / df_q3_['Ratings']
df_q3_com_['var2'] = df_q3_['MRP']
df_q3_com_['var3'] = df_q3_['current_price']/df_q3_['MRP']
df_q3_com_['var4'] = df_q3_['channel'].str.contains('Netflix') + 0
df_q3_com_['var5'] = df_q3_['channel'].str.contains('Prime Video') + 0
df_q3_com_['var6'] = df_q3_['Picture_quality'].str.contains('4K|8K') + 0
df_q3_com_ = df_q3_com_.dropna()
df_q3_com_


df_q3_model_ = RandomForestRegressor(random_state=123)
df_q3_model_X = df_q3_com_.drop(columns = 'Stars')
df_q3_model_y = df_q3_com_['Stars']
df_q3_model_.fit(X = df_q3_model_X,
                 y = df_q3_model_y)
column_max_index = df_q3_model_.feature_importances_.argmax()
df_q3_model_X.columns[column_max_index], df_q3_model_.feature_importances_

('var3',
 array([0.31220617, 0.17383963, 0.4446912 , 0.02714087, 0.02400442,
        0.01811773]))

---
## 단계별

In [110]:
df_q3 = df.copy()
df_q3_com = pd.DataFrame()

In [87]:
df_q3 = df_q3.loc[~df_q3['channel'].str.contains("Pixel|Oper"),].reset_index(drop=True)


"""
* ※ channel 변수에 해상도('Pixel' 문자 참조) 또는 운영체제 정보('Oper' 문자 참조)가 있는 TV는 분석에서 제외하시오.
"""
df_q3_com = pd.DataFrame()
df_q3_com['Stars'] = df_q3['Stars'].copy()
df_q3_com['var1'] = df_q3['Reviews'] / df_q3['Ratings']
df_q3_com['var2'] = df_q3['MRP']
df_q3_com['var3'] = df_q3['current_price'] / df_q3['MRP']
"""
* ※ Netflix와 Prime Video 제공 여부 변수는 channel 변수를 참고하시오.
"""
df_q3_com['var4'] = df_q3['channel'].str.contains('Netfilx') + 0 #제공 1 미제공 0
df_q3_com['var5'] = df_q3['channel'].str.contains('Prime Video') + 0 #제공 1 미제공 0

"""
* ※ 고해상도 여부 변수 생성은 해상도(Picture_quality) 변수만 참고하여 생성하시오.
"""
df_q3_com['var6'] = df_q3['Picture_quality'].str.contains('4K|8K') + 0
"""
* ※ 독립변수를 생성하면서 결측치가 생성되는 경우 해당 행을 모두 제거하시오.
"""
df_q3_com = df_q3_com.dropna().reset_index(drop=True) # df_q3_com.dropna()만 하면 안됨
"""
* ※ 학습 대상이 되는 행 개수는 197이다.
"""
df_q3_com.isna().sum()

Stars    0
var1     0
var2     0
var3     0
var4     0
var5     0
var6     0
dtype: int64

In [85]:
df_q3_com

     Stars      var1   var2      var3  var4  var5  var6
0      3.8  0.137941  21999  0.395427     0     0     0
1      4.4  0.088577  21990  0.750296     0     1     0
2      4.3  0.090750  21999  0.749989     0     1     0
3      4.3  0.097756  24999  0.619985     0     1     0
4      4.4  0.089692  22900  0.698646     0     0     0
..     ...       ...    ...       ...   ...   ...   ...
192    4.0  0.158607  19500  0.691795     0     0     0
193    4.4  0.177431  43990  0.840873     0     1     1
194    4.4  0.146341  27990  0.821686     0     1     0
195    4.4  0.215753  31900  0.860470     0     0     0
196    4.5  0.178666  68400  0.499766     0     1     1

[197 rows x 7 columns]

아래 절차를 수행하여 변수 중요도를 확인하고, **변수 중요도 값 중 가장 큰 값을 가진 변수명을 기술하시오.**

In [ ]:
#모델 정의
df_q3_randomforest = RandomForestRegressor(random_state = 123)
#fit 학습
df_q3_randomforest.fit(X = df_q3_com.drop(columns="Stars"),
                       y = df_q3_com['Stars'])
df_q3_randomforest.feature_importances_.argmax()

2

In [102]:
df_q3_com.drop(columns="Stars").columns[df_q3_randomforest.feature_importances_.argmax()]

'var3'